language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "no dependencies"

# Scripts to be run such as tests
before_script:
  - echo "run testing"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed chiennh2/udagram-api-feed:0.1
  - docker tag udagram-api-user chiennh2/udagram-api-user:0.1
  - docker tag udagram-frontend chiennh2/udagram-frontend:0.1
  - docker tag udagram-reverseproxy chiennh2/reverseproxy:0.1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chiennh2/udagram-api-feed:v1
  - docker push chiennh2/udagram-api-user:v1
  - docker push chiennh2/udagram-frontend:v1
  - docker push chiennh2/reverseproxy:v1
